(define (print line)
    (display line)
    (newline))

; Set representation as unordered list
(define (element-of-set? x set)
  (cond ((null? set) #f)
        ((equal? (car set) x) #t)
        (else (element-of-set? x (cdr set)))))
(define (adjoin-set x set)
  (if (element-of-set? x set)
      set
      (cons x set)))
(define (intersection-set set1 set2)
  (cond ((or (null? set1) (null? set2))
          '())
        ((element-of-set? (car set1) set2)
          (cons (car set1) (intersection-set (cdr set1)
                                             set2)))
        (else (intersection-set (cdr set1) set2))))
(define (union-set set1 set2)
  (cond ((or (null? set1) (null? set2))
          set2)
        ((element-of-set? (car set1) set2)
          (union-set (cdr set1) set2))
        (else 
          (cons (car set1) (union-set (cdr set1) set2)))))

(define test (list 3 4 5 6 7 8))
(define test2 (list 1 2 3))
(print (intersection-set test test2))
(print (union-set test test2))
