(define (print line)
  (display line)
  (newline))

; SELECTOR
(define (front-ptr deque) (car deque))
(define (rear-ptr deque) (cdr deque))
(define (set-front-ptr! deque item) 
  (set-car! deque item))
(define (set-rear-ptr! deque item) 
  (set-cdr! deque item))
(define (empty-deque? deque)
  (null? (front-ptr deque)))
(define (front-deque deque)
  (caar (front-ptr deque)))
(define (rear-deque deque)
  (caar (rear-ptr deque)))
(define (front-item-pair deque)
  (car (front-ptr deque)))
(define (rear-item-pair deque)
  (car (rear-ptr deque)))

; CONSTRUCTOR
(define (make-deque) (cons '() '()))

; MUTATOR
(define (front-insert-deque! deque item)
  (let ((pointer-pair (cons '() '())))
    (let ((new-pair (cons item '())))
      (cond ((empty-deque? deque)
              (set-car! pointer-pair new-pair)
              (set-front-ptr! deque pointer-pair)
              (set-rear-ptr! deque pointer-pair))
            (else
              (set-cdr! (front-item-pair deque) pointer-pair)
              (set-cdr! pointer-pair (front-ptr deque))
              (set-car! pointer-pair new-pair)
              (set-front-ptr! deque pointer-pair))))))

(define (rear-insert-deque! deque item)
  (let ((pointer-pair (cons '() '())))
    (let ((new-pair (cons item '())))
      (cond ((empty-deque? deque)
              (set-car! pointer-pair new-pair)
              (set-front-ptr! deque pointer-pair)
              (set-rear-ptr! deque pointer-pair))
            (else
              (set-cdr! new-pair (rear-ptr deque))
              (set-rear-ptr! deque pointer-pair)
              (set-car! pointer-pair new-pair))))))

(define (front-delete-deque! deque)
  (if (empty-deque? deque)
      (error "DELETE-FRONT! deque but empty" deque)
      (begin (set-front-ptr! deque (cdr (front-ptr deque)))
             (set-cdr! (front-item-pair deque) '()))))
(define (rear-delete-deque! deque)
  (if (empty-deque? deque)
      (error "DELETE-REAR! deque but empty" deque)
      (begin (set-rear-ptr! deque (cdr (rear-item-pair deque)))
             (set-cdr! (rear-item-pair deque) '()))))

(define d1 (make-deque))
(front-insert-deque! d1 'a)
(print d1)
(front-insert-deque! d1 'b)
(rear-insert-deque! d1 'c)
(print d1)
(print (front-deque d1))
(print (rear-deque d1))
