(define (print line)
  (display line)
  (newline))

(define (make-account balance real-password)
  (define wrong-password 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input-password req)
    (cond ((not (eq? input-password real-password))
            (begin (set! wrong-password (+ wrong-password 1))
                   "Incorrect password"))
          ((eq? req 'withdraw) withdraw)
          ((eq? req 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       req))))
  dispatch)

