(define (print line)
  (display line)
  (newline))

(define (make-account balance real-password)
  (define wrong-password 0)
  (define (call-the-cop x)
    (error "POLICE CAR SOUND YOU BETTER RUN"))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch input-password req)
    (cond ((not (eq? input-password real-password))
            (begin (set! wrong-password (+ wrong-password 1))
                   (if (= wrong-password 7)
                       call-the-cop
                       (lambda (x) "Incorrect password"))))
          ((eq? req 'withdraw) withdraw)
          ((eq? req 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       req))))
  dispatch)

(define acc (make-account 500 'password))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
(print ((acc 'pass 'deposit) 200))
