(define (make-table)
  (let ((local-table (list '*table*))
        (number-of-key 0))
    (define (assoc record . key-list)...)
    (define (lookup table . key-list) ...)
    (define (insert! table value . key-list). ..)
    (define (dispatch m)
      (cond ((eq? m 'lookup) lookup)
            ((eq? m 'insert!) insert)
            (else (error "UNKNOWN request -- " m))))
    (dispatch)))
